[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
borsh = { workspace = true }
schemars = { workspace = true } 